name: Build and deploy Node.js app to Azure Web App - brennand-tower

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, generate, build, and test
        working-directory: ./backend  # Ensures all commands run in backend directory
        run: |
          npm ci  # Using ci instead of install for more reliable builds
          npx prisma generate
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./backend/dist
            ./backend/node_modules
            ./backend/package.json
            ./backend/package-lock.json
            ./backend/prisma

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8A0778C53EC41C6A957FA8F01352512 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E2BE206AF1244CC7AB25398BA9BAD7A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0D1CF7C29B8544C894B83F7A9BB89439 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'brennand-tower'
          slot-name: 'Production'
          package: .
