name: Deploy Frontend to Azure Web App

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências e build do React
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: brennandbbfrontend
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          package: ./frontend/build
